version: "3.3"

services: 
    mariadb:
        image: mariadb:10
        environment: 
            MYSQL_DATABASE: node_shop_01
            MYSQL_USER: ns01
            MYSQL_PASSWORD: change-me
            MYSQL_ROOT_PASSWORD: change-me-also
        volumes: 
            - mdb:/var/lib/mysql
        ports: 
            - 3306:3306
        networks: 
            - linknet
            
    http_server:
        image: s:latest
        ports: 
            - 9009:9009
        networks: 
            - linknet
        environment: 
            PORT: 9009
            DB_HOST: mariadb
            DB_PORT: 3306
            DB_NAME: node_shop_01
            DB_USER: ns01
            DB_PASSWORD: change-me
            RUN: dev
        
networks: 
    linknet:

volumes: 
    mdb:
    
