openapi: '3.0.2'
info:
  title: Node_Shop
  version: '1.0'
servers:
  - url: http://localhost:9003
paths:
  /:
    get:
      responses:
        '200':
          description: Serves the entrypoint which loads the React application
  /app.js:
    get:
      responses:
        '200':
          description: Serves the built js bundle required by the entrypoint
  
  /login:
    post:
      responses:
        '200':
          description: Login credentials AJAX to endpoint
        '400':
          description: Bad Request
  
  /register:
    post:
      responses:
        '200':
          description: Register user is processed by the server endpoint
        '400':
          description: Bad Request 

  /item/:id:
    get:
      description: item_id passed as slug in the url.
      responses:
        '200':
          description: The id must be passed as slug in the url, serves an item / product with all available data.
          content:
            application/json:
              example:
                body:    ' {
        "name": "Samsung Galaxy S21 MAX",
        "description": "Lorem Ipsum",
        "price": 800,
        "images": "{\"urls\": null}"
    }'

        '404':
          description: Item not found.

    delete:
      description: id passed as parameter, 
      responses:
        '200':
          description: Serves an item / product with all available data.
          content:
            application/json:
              example:
                item: Object<any>

        '404':
          description: Item not found.
  /item:
    post:
      requestBody:
          description: item_id passed as parameter.
          content:
            application/json:
              schema:
                  type: object
              example:
                body: '{"name":"Samsung Galaxy S11","description":"Lorem Ipsum","price":750.00}'
      responses:
        '200':
          description: Inserts an item in the database. (Requires authentication)
        '403':
          description: Forbidden - Unauthenticated request to the endpoint.
        '400':
          description: Bad Request
    patch:
      responses:
        '200':
          description: Update an item in the database. (Requires authentication)
          content:
            application/json:
              schema:
                  type: object
              example:
                body: '[{"name":"Samsung Galaxy S11"},{"id":3}]'
        
        '403':
          description: Forbidden - Unauthenticated request to the endpoint.
        '400':
          description: Bad Request
        '404':
          description: Item not found
    
  /items:
    get:
      responses:
        '200':
          description: Serves the list of items with summary description of each of them.

  /orders:
    get:
      responses:
        '200':
          description: Serves the list of orders with summary description of each of them.


  /order:
    get:
      responses:
        '200':
          description: Gets the specified order data and the user that initiated it. (Requires authentication)
        '403':
          description: Forbidden - Unauthenticated request to the endpoint.
        '404':
          description: Order not found.

    post:
      responses:
        '200':
          description: Created a new order. (Requires authentication)
        '403':
          description: Forbidden - Unauthenticated request to the endpoint.
        '400':
          description: Bad Request
    patch:
      responses:
        '200':
          description: Update an existing order. (Requires authentication)
        '403':
          description: Forbidden - Unauthenticated request to the endpoint.
        '400':
          description: Bad Request
        '404':
          description: Order not found.


